const fs = require('fs');
const path = require('path');

const schemaDir = path.join(__dirname, '..', 'schema');
const outputFile = path.join(__dirname, '..', 'schema.prisma');

const header = `// Prisma schema for the auth + users + audit scope.
// Mirrors the existing MySQL schema (migrations 001, 004, 005) so the generated
// client matches columns used by application code. Other modules (employees,
// notebooklm, vocabulary) keep using mysql2 directly and are out of scope.
//
// NOTE: This file is auto-generated from the files in ./schema/.
// Do not edit this file directly; edit the per-table files and run:
//   node scripts/merge-schema.js
// このファイルは ./schema/ 内のファイルから自動生成されます。
// 直接編集せず、テーブルごとのファイルを編集して上記コマンドを実行してください。

generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "mysql"
  url      = env("DATABASE_URL")
}
`;

const files = [
  'user.prisma',
  'audit_log.prisma',
  'role.prisma',
  'setting.prisma',
  'vocabulary.prisma',
  'vocab_relation.prisma',
  'vocab_change_log.prisma',
  'vocab_report.prisma',
  'workspace.prisma',
  'workspace_member.prisma',
  'document.prisma',
  'job.prisma',
  'job_step.prisma',
  'chat_session.prisma',
  'chat_message.prisma',
  'dead_letter_job.prisma',
];

const models = files
  .map((file) => {
    const filePath = path.join(schemaDir, file);
    if (!fs.existsSync(filePath)) {
      throw new Error(`Missing schema file: ${filePath}`);
    }
    return fs.readFileSync(filePath, 'utf8').trim();
  })
  .join('\n\n');

fs.writeFileSync(outputFile, header + '\n' + models + '\n');
console.log(`Merged ${files.length} schema files into ${outputFile}`);
