"""
Mock Ollama HTTP server for local development / testing without a real Ollama instance.
/ 本物のOllamaサーバーがない場合の開発・テスト用モックサーバー

Usage / 使い方:
    python python-services/mock_ollama_server.py [--port 11434] [--delay 0.5]

Endpoints emulated / エミュレートするエンドポイント:
    POST /api/generate     → returns a canned RAG-style answer
    GET  /api/tags         → returns a fake model list (for health checks)

Environment variables / 環境変数:
    MOCK_OLLAMA_PORT    Override listening port  (default: 11434)
    MOCK_OLLAMA_DELAY   Simulated latency in seconds (default: 0.2)
"""
from __future__ import annotations

import argparse
import json
import os
import textwrap
import time
from http.server import BaseHTTPRequestHandler, HTTPServer
from typing import Any


# ---------------------------------------------------------------------------
# Response templates / レスポンステンプレート
# ---------------------------------------------------------------------------

_FAKE_MODELS = {
    "models": [
        {
            "name": "llama3:latest",
            "modified_at": "2026-01-01T00:00:00Z",
            "size": 0,
        }
    ]
}


def _build_generate_response(model: str, prompt: str) -> dict[str, Any]:
    """
    Build a deterministic fake LLM answer that echoes key parts of the prompt.
    / プロンプトの要点を反映した決定論的な偽LLM回答を構築する。
    """
    # Extract question from prompt (after "Question:" marker)
    # / プロンプトから質問テキストを抽出する
    question = ""
    for line in prompt.splitlines():
        if line.startswith("Question:"):
            question = line.replace("Question:", "").strip()
            break

    if not question:
        # Fallback: use last non-empty line / フォールバック: 最後の非空行を使用
        lines = [l.strip() for l in prompt.splitlines() if l.strip()]
        question = lines[-1] if lines else "your question"

    answer = textwrap.dedent(f"""\
        [Mock Ollama – {model}]

        Based on the provided document context, here is a synthesized answer to:
        "{question}"

        The documents contain relevant information about this topic. \
In a real deployment this response would be generated by the language model \
using the retrieved context chunks. \
This mock response confirms that the RAG pipeline, job queue, and \
chat message storage are all wired up correctly.
    """).strip()

    return {
        "model": model,
        "created_at": "2026-01-01T00:00:00.000000Z",
        "response": answer,
        "done": True,
        "done_reason": "stop",
        "context": [],
        "total_duration": 500_000_000,
        "load_duration": 100_000_000,
        "prompt_eval_count": len(prompt.split()),
        "eval_count": len(answer.split()),
    }


# ---------------------------------------------------------------------------
# HTTP handler / HTTPハンドラ
# ---------------------------------------------------------------------------

class OllamaMockHandler(BaseHTTPRequestHandler):
    """Handles incoming HTTP requests and returns mock Ollama responses."""

    # Simulated response delay in seconds / 応答遅延シミュレーション
    delay: float = 0.2

    def log_message(self, fmt: str, *args: Any) -> None:  # noqa: ANN001
        # Use a cleaner log format / より見やすいログ形式
        print(f"[mock-ollama] {self.address_string()} → {fmt % args}")

    def _send_json(self, status: int, body: dict[str, Any]) -> None:
        payload = json.dumps(body, ensure_ascii=False).encode("utf-8")
        self.send_response(status)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(payload)))
        self.end_headers()
        self.wfile.write(payload)

    def _read_json_body(self) -> dict[str, Any]:
        length = int(self.headers.get("Content-Length", 0))
        raw = self.rfile.read(length) if length else b"{}"
        try:
            return json.loads(raw.decode("utf-8"))
        except json.JSONDecodeError:
            return {}

    # ------------------------------------------------------------------
    # Route handlers / ルートハンドラ
    # ------------------------------------------------------------------

    def do_GET(self) -> None:  # noqa: N802
        if self.path == "/api/tags":
            self._send_json(200, _FAKE_MODELS)
        else:
            self._send_json(404, {"error": f"unknown endpoint: {self.path}"})

    def do_POST(self) -> None:  # noqa: N802
        if self.path == "/api/generate":
            body = self._read_json_body()
            model = str(body.get("model") or "llama3")
            prompt = str(body.get("prompt") or "")

            # Simulate processing time / 処理時間シミュレーション
            time.sleep(self.delay)

            response = _build_generate_response(model, prompt)
            self._send_json(200, response)
        else:
            self._send_json(404, {"error": f"unknown endpoint: {self.path}"})


# ---------------------------------------------------------------------------
# Entry point / エントリポイント
# ---------------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(description="Mock Ollama server for development")
    parser.add_argument(
        "--port",
        type=int,
        default=int(os.environ.get("MOCK_OLLAMA_PORT", "11434")),
        help="Port to listen on (default: 11434)",
    )
    parser.add_argument(
        "--delay",
        type=float,
        default=float(os.environ.get("MOCK_OLLAMA_DELAY", "0.2")),
        help="Simulated response delay in seconds (default: 0.2)",
    )
    args = parser.parse_args()

    OllamaMockHandler.delay = args.delay

    server = HTTPServer(("0.0.0.0", args.port), OllamaMockHandler)
    print(
        f"[mock-ollama] Listening on http://0.0.0.0:{args.port}\n"
        f"[mock-ollama] Simulated delay: {args.delay}s\n"
        f"[mock-ollama] Set LLM_API_URL=http://localhost:{args.port} in your .env\n"
        f"[mock-ollama] Press Ctrl+C to stop."
    )
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        print("\n[mock-ollama] Stopped.")


if __name__ == "__main__":
    main()
